name = "NaturallyUnitful"
uuid = "872cf16e-200e-11e9-2cdf-8bb39cfbec41"
authors = ["MasonProtter <mason.protter@gmail.com>"]
version = "0.3.0"

[deps]
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
julia = "1"
